import { Injectable } from '@angular/core';
import { jsPDF } from 'jspdf';
import { type PaymentJourneyResult } from './payment.models';
import { formatCurrencyAmount, formatDateTime } from './shared/formatting';

interface ProofRow {
  label: string;
  value: string;
}

@Injectable({ providedIn: 'root' })
export class PaymentProofService {
  private logoDataUrlPromise: Promise<string | null> | null = null;

  async downloadProof(result: PaymentJourneyResult): Promise<void> {
    const pdf = await this.buildDocument(result);
    pdf.save(this.buildFileName(result));
  }

  async openPrintView(result: PaymentJourneyResult): Promise<boolean> {
    const pdf = await this.buildDocument(result);
    const blobUrl = URL.createObjectURL(pdf.output('blob'));
    const popup = globalThis.open(blobUrl, '_blank', 'noopener,noreferrer');

    if (!popup) {
      URL.revokeObjectURL(blobUrl);
      return false;
    }

    popup.focus();
    setTimeout(() => URL.revokeObjectURL(blobUrl), 120000);

    return true;
  }

  buildEmailSubject(result: PaymentJourneyResult): string {
    return `Proof of payment - ${result.submission.reference}`;
  }

  buildEmailBody(result: PaymentJourneyResult): string {
    const amount = formatCurrencyAmount(result.submission.amount, result.submission.currency);

    return [
      'Proof of payment',
      '',
      `Reference: ${result.submission.reference}`,
      `Amount: ${amount}`,
      `Sender account: ${result.submission.senderAccountNumber}`,
      `Receiver account: ${result.submission.receiverAccountNumber}`,
      `Transaction ID: ${result.response.transactionId ?? 'Not issued'}`,
      `Payment reference ID: ${result.submission.clientReference}`,
      `Recorded: ${formatDateTime(result.payment.createdAt)}`,
      '',
      'Generated by Instant Payment Namibia.'
    ].join('\n');
  }

  buildSmsBody(result: PaymentJourneyResult): string {
    return [
      'Proof of payment',
      formatCurrencyAmount(result.submission.amount, result.submission.currency),
      `Ref ${result.submission.reference}`,
      `Txn ${result.response.transactionId ?? 'Pending'}`
    ].join(' | ');
  }

  private async buildDocument(result: PaymentJourneyResult): Promise<jsPDF> {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'a4',
      compress: true,
      putOnlyUsedFonts: true
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 42;
    // Keep the proof close to document typography instead of screen UI scale.
    const type = {
      title: 18,
      headerMeta: 9,
      eyebrow: 9,
      heroTitle: 16,
      body: 10.5,
      cardLabel: 8.5,
      cardValue: 11.5,
      amountValue: 15,
      sectionTitle: 12,
      tableValue: 10.5,
      footer: 8.5
    };
    const statusColor = result.response.status === 'SUCCESS' ? [30, 120, 64] : [153, 51, 51];
    const softStatusColor = result.response.status === 'SUCCESS' ? [235, 246, 239] : [249, 239, 239];
    const logoDataUrl = await this.loadLogoDataUrl();
    const assessmentDisclaimer =
      'Assessment environment. This practical test site is for technical evaluation only and must not be used for live payments.';

    pdf.setFillColor(255, 253, 247);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');

    pdf.setFillColor(153, 51, 51);
    pdf.rect(0, 0, pageWidth, 78, 'F');
    pdf.setFillColor(153, 153, 102);
    pdf.rect(0, 78, pageWidth, 8, 'F');

    if (logoDataUrl) {
      pdf.addImage(logoDataUrl, 'PNG', margin, 18, 40, 40);
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(type.title);
    pdf.setTextColor(255, 255, 255);
    pdf.text('Proof of Payment', pageWidth - margin, 34, { align: 'right' });

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(type.headerMeta);
    pdf.text('Bank of Namibia | Instant Payment Namibia', pageWidth - margin, 52, { align: 'right' });
    pdf.text(`Generated ${formatDateTime(new Date())}`, pageWidth - margin, 64, { align: 'right' });

    const noticeY = 100;
    pdf.setFillColor(252, 244, 232);
    pdf.setDrawColor(232, 224, 211);
    pdf.roundedRect(margin, noticeY, pageWidth - margin * 2, 34, 10, 10, 'FD');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8.5);
    pdf.setTextColor(153, 51, 51);
    pdf.text('ASSESSMENT NOTICE', margin + 12, noticeY + 14);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8.5);
    pdf.setTextColor(109, 90, 76);
    const disclaimerLines = pdf.splitTextToSize(assessmentDisclaimer, pageWidth - margin * 2 - 24);
    pdf.text(disclaimerLines, margin + 12, noticeY + 26);

    const heroY = 146;
    pdf.setFillColor(255, 255, 255);
    pdf.setDrawColor(232, 224, 211);
    pdf.roundedRect(margin, heroY, pageWidth - margin * 2, 96, 14, 14, 'FD');

    pdf.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
    pdf.circle(margin + 38, heroY + 30, 20, 'F');
    this.drawStatusSymbol(pdf, margin + 38, heroY + 30, result.response.status === 'SUCCESS');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(type.eyebrow);
    pdf.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    pdf.text(result.response.status === 'SUCCESS' ? 'Transaction complete' : 'Transaction not completed', margin + 74, heroY + 18);

    pdf.setFontSize(type.heroTitle);
    pdf.setTextColor(50, 38, 29);
    pdf.text(result.response.status === 'SUCCESS' ? 'Payment successful' : 'Payment failed', margin + 74, heroY + 42);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(type.body);
    pdf.setTextColor(109, 90, 76);
    const messageLines = pdf.splitTextToSize(result.response.message, 255);
    pdf.text(messageLines, margin + 74, heroY + 60);

    pdf.setFillColor(softStatusColor[0], softStatusColor[1], softStatusColor[2]);
    pdf.roundedRect(pageWidth - margin - 170, heroY + 18, 140, 56, 12, 12, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(type.cardLabel);
    pdf.setTextColor(109, 90, 76);
    pdf.text('Amount', pageWidth - margin - 150, heroY + 34);
    pdf.setFontSize(type.amountValue);
    pdf.setTextColor(50, 38, 29);
    pdf.text(formatCurrencyAmount(result.submission.amount, result.submission.currency), pageWidth - margin - 150, heroY + 56);

    const metaCardsY = heroY + 116;
    const metaCardGap = 14;
    const metaCardWidth = (pageWidth - margin * 2 - metaCardGap) / 2;
    this.drawInfoCard(pdf, margin, metaCardsY, metaCardWidth, 'Transaction ID', result.response.transactionId ?? 'Not issued');
    this.drawInfoCard(pdf, margin + metaCardWidth + metaCardGap, metaCardsY, metaCardWidth, 'Payment reference ID', result.submission.clientReference);
    this.drawInfoCard(pdf, margin, metaCardsY + 68, metaCardWidth, 'Recorded', formatDateTime(result.payment.createdAt));
    this.drawInfoCard(pdf, margin + metaCardWidth + metaCardGap, metaCardsY + 68, metaCardWidth, 'Channel', 'Instant Payment Namibia');

    const partyY = metaCardsY + 150;
    this.drawPartyCard(pdf, margin, partyY, metaCardWidth, 'Sender account', result.submission.senderAccountNumber);
    this.drawPartyCard(pdf, margin + metaCardWidth + metaCardGap, partyY, metaCardWidth, 'Receiver account', result.submission.receiverAccountNumber);

    const transactionRows: ProofRow[] = [
      { label: 'Status', value: result.response.status },
      { label: 'Amount', value: formatCurrencyAmount(result.submission.amount, result.submission.currency) },
      { label: 'Reference', value: result.submission.reference },
      { label: 'Currency', value: result.submission.currency },
      { label: 'Message', value: result.response.message },
      { label: 'Error code', value: result.response.errorCode ?? 'Not applicable' }
    ];

    const tableY = partyY + 88;
    this.drawSectionTable(pdf, margin, tableY, pageWidth - margin * 2, 'Transaction details', transactionRows);

    pdf.setDrawColor(222, 215, 203);
    pdf.line(margin, pageHeight - 70, pageWidth - margin, pageHeight - 70);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(type.footer);
    pdf.setTextColor(109, 90, 76);
    const footerNote = pdf.splitTextToSize(
      'Assessment environment. This system-generated proof is for technical evaluation only, reflects the recorded payment outcome, and must not be used for live payments.',
      pageWidth - margin * 2 - 120
    );
    pdf.text(footerNote, margin, pageHeight - 50);

    pdf.setFont('helvetica', 'bold');
    pdf.text('Bank of Namibia', pageWidth - margin, pageHeight - 48, { align: 'right' });
    pdf.setFont('helvetica', 'normal');
    pdf.text('Instant Payment Namibia', pageWidth - margin, pageHeight - 36, { align: 'right' });

    return pdf;
  }

  private drawStatusSymbol(pdf: jsPDF, centerX: number, centerY: number, success: boolean): void {
    pdf.setDrawColor(255, 255, 255);
    pdf.setLineWidth(4);

    if (success) {
      pdf.line(centerX - 10, centerY + 1, centerX - 2, centerY + 10);
      pdf.line(centerX - 2, centerY + 10, centerX + 12, centerY - 8);
      pdf.setLineWidth(1);
      return;
    }

    pdf.line(centerX - 7, centerY - 7, centerX + 7, centerY + 7);
    pdf.line(centerX + 7, centerY - 7, centerX - 7, centerY + 7);
    pdf.setLineWidth(1);
  }

  private drawInfoCard(pdf: jsPDF, x: number, y: number, width: number, label: string, value: string): void {
    pdf.setFillColor(255, 255, 255);
    pdf.setDrawColor(232, 224, 211);
    pdf.roundedRect(x, y, width, 54, 10, 10, 'FD');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8.5);
    pdf.setTextColor(109, 90, 76);
    pdf.text(label.toUpperCase(), x + 14, y + 17);

    pdf.setFontSize(11);
    pdf.setTextColor(50, 38, 29);
    const valueLines = pdf.splitTextToSize(value, width - 28);
    pdf.text(valueLines, x + 14, y + 35);
  }

  private drawPartyCard(pdf: jsPDF, x: number, y: number, width: number, label: string, value: string): void {
    pdf.setFillColor(245, 238, 224);
    pdf.setDrawColor(232, 224, 211);
    pdf.roundedRect(x, y, width, 74, 12, 12, 'FD');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8.5);
    pdf.setTextColor(109, 90, 76);
    pdf.text(label.toUpperCase(), x + 16, y + 19);

    pdf.setFontSize(13.5);
    pdf.setTextColor(50, 38, 29);
    pdf.text(value, x + 16, y + 41);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9.5);
    pdf.setTextColor(109, 90, 76);
    pdf.text('Account', x + 16, y + 58);
  }

  private drawSectionTable(pdf: jsPDF, x: number, y: number, width: number, title: string, rows: ReadonlyArray<ProofRow>): void {
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(50, 38, 29);
    pdf.text(title, x, y);

    let rowY = y + 14;
    const labelWidth = 132;

    for (const row of rows) {
      const valueLines = pdf.splitTextToSize(row.value, width - labelWidth - 28);
      const rowHeight = Math.max(30, valueLines.length * 11 + 16);

      pdf.setFillColor(255, 255, 255);
      pdf.setDrawColor(232, 224, 211);
      pdf.rect(x, rowY, width, rowHeight, 'FD');

      pdf.setFillColor(248, 243, 234);
      pdf.rect(x, rowY, labelWidth, rowHeight, 'F');
      pdf.line(x + labelWidth, rowY, x + labelWidth, rowY + rowHeight);

      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(8.5);
      pdf.setTextColor(109, 90, 76);
      pdf.text(row.label.toUpperCase(), x + 14, rowY + 18);

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10.5);
      pdf.setTextColor(50, 38, 29);
      pdf.text(valueLines, x + labelWidth + 14, rowY + 18);

      rowY += rowHeight;
    }
  }

  private buildFileName(result: PaymentJourneyResult): string {
    const cleanedReference = result.submission.reference.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const referencePart = cleanedReference || 'transaction';
    return `proof-of-payment-${referencePart}-${result.submission.clientReference}.pdf`;
  }

  private loadLogoDataUrl(): Promise<string | null> {
    if (this.logoDataUrlPromise) {
      return this.logoDataUrlPromise;
    }

    this.logoDataUrlPromise = fetch('/bon-logo.png')
      .then(async (response) => {
        if (!response.ok) {
          return null;
        }

        const blob = await response.blob();
        return await new Promise<string | null>((resolve) => {
          const reader = new FileReader();
          reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : null);
          reader.onerror = () => resolve(null);
          reader.readAsDataURL(blob);
        });
      })
      .catch(() => null);

    return this.logoDataUrlPromise;
  }
}
